### ISSUE TITLE
Cannot read property 'content' of undefined     at Object.optimizationLoader

### ISSUE THREAD

**Issue by HugoHeneault** [asotog/squeezebox#13]
I have this error while trying to compile squeezebox in an ionic app with aot : `ionic cordova run ios --prod`

```
Error: ./node_modules/squeezebox/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 34:0-45
 @ ./src/app/main.ts,./node_modules/squeezebox/components/squeezebox.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/company-details/company-details.page.ngfactory.js 39:0-61
 @ ./src/pages/company-details/company-details.page.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/squeezebox/components/sb-item.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/company-details/company-details.page.ngfactory.js 41:0-58
 @ ./src/pages/company-details/company-details.page.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/squeezebox/components/sb-item-head.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/company-details/company-details.page.ngfactory.js 43:0-63
 @ ./src/pages/company-details/company-details.page.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/squeezebox/components/sb-item-body.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/mobile/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/pages/company-details/company-details.page.ngfactory.js 45:0-63
 @ ./src/pages/company-details/company-details.page.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
```

Any ideas?

**Comment by HugoHeneault** [comment]
According to https://github.com/ionic-team/ionic-app-scripts/issues/439, you should transpile your components before linking them to npm to avoid that kind of issues...

**Comment by asotog** [comment]
mm weird will check further later, we had some issues before but were fixed https://github.com/asotog/squeezebox/issues/8

**Comment by HugoHeneault** [comment]
Are the js files added while npm link? I ran tsc inside my node_modules folder container squeezebox and it's working now :)

**Comment by HugoHeneault** [comment]
For anyone having this issue until it's fixed:

```
cd node_modules/squeezebox
tsc
```

**Comment by asotog** [comment]
can you please try latest version 1.2.0 now compiled files are included, try removing the full `node_modules/squeezebox` directory first then install via npm

**Comment by asotog** [comment]
feel free to reopen this
